name: pais-triggers

on:
  workflow_dispatch:
    inputs:
      pais:
        description: 'País'
        required: true
        type: string

jobs:
  evaluar-pais:
    runs-on: ubuntu-latest
    steps:
      - name: Convertir país a minúsculas
        id: lowercase
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{ github.event.inputs.pais }}

      - name: Verificar si es país latino
        id: verificar
        run: |
          pais_lower=${{ steps.lowercase.outputs.lowercase }}
          echo "País en minúscula: $pais_lower"

          # Lista de países latinos
          lista='peru mexico argentina colombia chile brasil ecuador bolivia uruguay paraguay venezuela'

          if echo "$lista" | grep -qw "$pais_lower"; then
            echo "::set-output name=resultado::$pais_lower es un país de América Latina"
          else
            echo "::set-output name=resultado::$pais_lower NO es un país de América Latina"
          fi

      - name: Mostrar resultado
        run: echo "${{ steps.verificar.outputs.resultado }}"
