name: hola-mundo
on: [push]
jobs:
  saludo:
    runs-on: ubuntu-latest # Usa un runner de GitHub basado en Ubuntu
  
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Dar permiso de ejecucion al script
        run: chmod +x holamundo.sh

      - name: Ejecutar el script
        run: ./holamundo.sh